### ISSUE TITLE
Splitlines breaking lines inconsistent. Problem resolves when Refreshing Page

### ISSUE THREAD

**Issue by basboy12** [jeremyharris/split_lines#11]
Hi!

I'm using the Split lines function on https://omarboubess.webflow.io, wrapping each line of headings and paragraphs with a span. 

It seems like it's not working correctly for some elements, and breaks the line randomly by words, instead of actual lines. For example, check out the image attached, where you can see the paragraph is broken up incorrectly. 

The strange thing is, whenever I refresh the page, it seems to work fine. But when I enter the site's domain name in the address bar and hit enter, it always end up looking weird. 

Any idea what might the cause of this (and how to solve it?)

This is the code I'm using to select the right items:

```
    $( '.text-animation, p, :header' ).not('.exclude-animation').each(function( index, i ) {     
      $(this).splitLines({ tag: '<span class="text-reveal-mask"> <span class="text-reveal-wrap" loaded="false">' });
    });
```

![IMG_6565](https://user-images.githubusercontent.com/12978468/90180549-7038b000-ddaf-11ea-85ec-6ea5753e51fe.PNG)

![IMG_6566](https://user-images.githubusercontent.com/12978468/90180444-43849880-ddaf-11ea-9067-411ec2f206cf.PNG)

**Comment by jeremyharris** [comment]
I think this might have to do with the font loading. The way splitLines works is by calculating how much of the text can fit on a line before splitting it up. If the font you're using isn't loaded yet, then the calculations might be different as it would be calculating that based on the current font.

So, on initial load it doesn't have your font loaded so it calculates and splits differently, your fonts loads, and wraps the text (since it's wider than `sans-serif`). Then on the second request the font is already loaded/cached and splitLines calculates based on the loaded font's width.

A solution might be to try and detect if your font is loaded before splitting lines, although that's not a trivial task in and of itself. There's not really much splitLines can do here unfortunately.

Another possible solution would be force a width by using the `width` option in the splitLines plugin. This might fix the problem.
